load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "hello-world",
    srcs = ["hello-world.cc"],
    hdrs = ["hello-world.h"],
    visibility = ["//src/llvm-backend/main:__pkg__"],
)
