[@@@coverage exclude_file]

(* Since only used as a pprint function by Alcotest - called if lexer tests fail *)

open Parser

let pprint_tokens ppf = function
  | LPAREN           -> Fmt.pf ppf "LPAREN@."
  | RPAREN           -> Fmt.pf ppf "RPAREN@."
  | LBRACE           -> Fmt.pf ppf "LBRACE@."
  | RBRACE           -> Fmt.pf ppf "RBRACE@."
  | LANGLE           -> Fmt.pf ppf "LANGLE@."
  | RANGLE           -> Fmt.pf ppf "RANGLE@."
  | COLONEQ          -> Fmt.pf ppf "COLONEQ@."
  | VAR              -> Fmt.pf ppf "VAR@."
  | TYPE_INT         -> Fmt.pf ppf "TYPE_INT@."
  | TYPE_BOOL        -> Fmt.pf ppf "TYPE_BOOL@."
  | TYPE_VOID        -> Fmt.pf ppf "TYPE_VOID@."
  | BORROWED         -> Fmt.pf ppf "BORROWED@."
  | LINEAR           -> Fmt.pf ppf "LINEAR@."
  | READ             -> Fmt.pf ppf "READ@."
  | LOCAL            -> Fmt.pf ppf "LOCAL@."
  | SUBORDINATE      -> Fmt.pf ppf "SUBORDINATE@."
  | LOCKED           -> Fmt.pf ppf "LOCKED@."
  | CAPABILITY       -> Fmt.pf ppf "CAPABILITY@."
  | SEMICOLON        -> Fmt.pf ppf "SEMICOLON@."
  | NEW              -> Fmt.pf ppf "NEW@."
  | LET              -> Fmt.pf ppf "LET@."
  | INT i            -> Fmt.pf ppf "INT(%d)@." i
  | TRUE             -> Fmt.pf ppf "TRUE@."
  | FALSE            -> Fmt.pf ppf "FALSE@."
  | ID var           -> Fmt.pf ppf "ID(%s)@." var
  | FUNCTION         -> Fmt.pf ppf "FUNCTION@."
  | FINISH           -> Fmt.pf ppf "FINISH@."
  | EQUAL            -> Fmt.pf ppf "EQUAL@."
  | EOF              -> Fmt.pf ppf "EOF@."
  | DOT              -> Fmt.pf ppf "DOT@."
  | CONSUME          -> Fmt.pf ppf "CONSUME@."
  | CONST            -> Fmt.pf ppf "CONST@."
  | COMMA            -> Fmt.pf ppf "COMMA@."
  | COLON            -> Fmt.pf ppf "COLON@."
  | CLASS            -> Fmt.pf ppf "CLASS@."
  | EXTENDS          -> Fmt.pf ppf "EXTENDS@."
  | GENERIC_TYPE     -> Fmt.pf ppf "GENERIC_TYPE@."
  | ASYNC            -> Fmt.pf ppf "ASYNC@."
  | IF               -> Fmt.pf ppf "IF@."
  | ELSE             -> Fmt.pf ppf "ELSE@."
  | REM              -> Fmt.pf ppf "REM@."
  | PLUS             -> Fmt.pf ppf "PLUS@."
  | OR               -> Fmt.pf ppf "OR@."
  | MULT             -> Fmt.pf ppf "MULT@."
  | MINUS            -> Fmt.pf ppf "MINUS@."
  | EXCLAMATION_MARK -> Fmt.pf ppf "EXCLAMATION_MARK@."
  | DIV              -> Fmt.pf ppf "DIV@."
  | AND              -> Fmt.pf ppf "AND@."
  | WHILE            -> Fmt.pf ppf "WHILE@."
  | FOR              -> Fmt.pf ppf "FOR@."
  | MAIN             -> Fmt.pf ppf "MAIN@."
  | PRINTF           -> Fmt.pf ppf "PRINTF@."
  | STRING str       -> Fmt.pf ppf "STRING(%s)@." str
